name: Setup Flutter
description: Downloads Flutter and installs dependencies
inputs:
  channel:
    description: Flutter channel to be used
    required: true
  version:
    description: Flutter version to be used
    required: true
runs:
  using: composite
  steps:
    - name: Cache Flutter and dependencies
      uses: actions/cache@v3
      with:
        path: ${{ runner.tool_cache }}/flutter
        key: flutter-${{ runner.os }}-${{ inputs.channel }}-${{ inputs.version }}-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          flutter-${{ runner.os }}-${{ inputs.channel }}-${{ inputs.version }}-

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: ${{ inputs.channel }}
        flutter-version: ${{ inputs.version }}

    - name: Pull dependencies
      run: flutter pub get
      shell: bash
