name: Tests (integration)

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          cache: true

      - name: Pull dependencies
        run: flutter pub get

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: playstore
          api-level: 31
          arch: x86_64
          profile: Pixel 5
          script: flutter test integration_test
