name: Main workflow

on:
  push:
    branches:
      - master

env:
  flutter-channel: master

jobs:
  lint:
    name: Lint + static analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter and dependencies
        uses: ./.github/actions/setup-flutter
        with:
          channel: ${{ env.flutter-channel }}

      - name: Run analysis
        run: dart analyze

  test:
    name: Tests (widget + unit)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter and dependencies
        uses: ./.github/actions/setup-flutter
        with:
          channel: ${{ env.flutter-channel }}

      - name: Run tests
        run: flutter test

  integration_test:
    name: Tests (integration)
    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [30, 31]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter and dependencies
        uses: ./.github/actions/setup-flutter
        with:
          channel: ${{ env.flutter-channel }}

      - name: Cache AVD snapshot
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Generate AVD snapshot for cache
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: playstore
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: pixel_4
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching"

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: playstore
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: pixel_4
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: flutter test integration_test
